src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity("email", "L' email existe déjà")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: 'Veuillez rentrer une adresse valide.')]
    #[Assert\NotBlank(message: 'Veuillez renseigner une adresse email.')]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\length(min: 6, minMessage: 'Le mot de passe doit faire plus de 6 caractères.')]
    #[Assert\NotBlank(message: 'Veuillez rentrer un mot de passe.')]
    private ?string $password = null;

    #[Assert\length(min: 6, minMessage: 'Le mot de passe doit faire plus de 6 caractères.')]
    private ?string $newPassword = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Veuillez renseigner votre prénom.')]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Veuillez renseigner votre nom.')]
    private ?string $lastname = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Question::class, orphanRemoval: true)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Vote::class, orphanRemoval: true)]
    private Collection $votes;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

      /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getNewPassword(): ?string
    {
        return $this->newPassword;
    }

    public function setNewPassword(string $newPassword): static
    {
        $this->newPassword = $newPassword;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setAuthor($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getAuthor() === $this) {
                $question->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): static
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setAuthor($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): static
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getAuthor() === $this) {
                $vote->setAuthor(null);
            }
        }

        return $this;
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $user = $builder->getData();

        $builder
            ->add('firstname', null , [ 'label' => '*Prénom'])
            ->add('lastname', null , [ 'label' => '*Nom'])
            ->add('pictureFile', FileType::class, [ 
                'label' => '*Image',
                'required' => $user?->getPicture() ? false : true,
                'mapped' => false,
                'constraints' => [
                    new Image([
                        'mimeTypesMessage' => 'Veuillez soumettre une image',
                        'maxSize' => '1M',
                        'maxSizeMessage' => 'Votre image fait {{ size }} {{ suffix }}. La limite est de  {{ limit }} {{ suffix }}'
                    ])
                ]
                ])
            ->add('email', null , [ 'label' => '*Courriel'])
            ->add('password', PasswordType::class, [ 'label' => '*Mot de passe']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\CommentRepository;
use App\Repository\QuestionRepository;
use App\Repository\VoteRepository;
use App\Service\Uploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserController extends AbstractController
{
    #[Route('/user/{id}', name: 'user')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function userProfile(User $user): Response
    {
        $currentUser = $this->getUser();

        if($currentUser === $user){
            return $this->redirectToRoute('current_user');
        }

        return $this->render('user/show.html.twig', [
            'user' => $user
        ]);
    }

    #[Route('/user', name: 'current_user')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function currentUserProfile(Uploader $uploader,Request $req, EntityManagerInterface $em, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user     = $this->getUser();
        $userForm = $this->createForm(UserType::class, $user);

        $userForm->remove('password');
        $userForm->add('newPassword', PasswordType::class, ['label' => 'Nouveau mot de passe', 'required' => false]);
        $userForm->handleRequest($req);
        if($userForm->isSubmitted() && $userForm->isValid())
        {
            $newPassword = $user->getNewPassword();
            if ($newPassword)
            {
                $hash = $passwordHasher->hashPassword($user, $newPassword);
                $user->setPassword($hash);
            }
            $picture = $userForm->get('pictureFile')->getData();
            if ($picture) {
                $user->setPicture($uploader->uploadProfileImage($picture, $user->getPicture()));
            }
            $em->flush();
            $this->addFlash('success', 'Modification utilisateur réussie');
            return $this->redirectToRoute('home');
        }

        return $this->render('user/index.html.twig', [
            'form' => $userForm->createView()
        ]);
    }

    #[Route('/user/questions/list', name: 'questions_user')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function questionUserProfile(QuestionRepository $questionRepo): Response
    {
        $user      = $this->getUser();
        $questions = $questionRepo->findBy(['author'  => $user ]);
        return $this->render('user/question.html.twig', [
            'user'      => $user,
            'questions' => $questions
        ]);
    }

    #[Route('/user/comments/list', name: 'comments_user')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function commentUserProfile(CommentRepository $commentRepo): Response
    {
        $user     = $this->getUser();
        $comments = $commentRepo->findBy(['author' => $user]);
        return $this->render('user/comment.html.twig', [
            'user'     => $user,
            'comments' => $comments
        ]);
    }
}

templates/user/comment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}

    <div class="block mb-20">
        <h3 class="pb-30">Mes réponses</h3>
        <ul>
        {% for comment in comments %}
            <li>
                <div class="pb-20 d-flex flex-row-nowrap justify-between align-center">
						<p  {% if comment.rating > 0 %} 
                                class="rating-up text-small mr-10" 
                            {% elseif comment.rating < 0 %} 
                                class="rating-down text-small mr-10" 
                            {% else %} 
                                class="text-small mr-10" 
                            {% endif %} >Vote: {{ comment.rating }}
                        </p>
						<p class="italic">{{ comment.createdAt | date("d/m/Y") }}</p>
					</div>
                <p class="pb-20">{{ comment.content }}</p>
            </li>
        {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}
    <div class="block mb-20">
        <h2 class="pb-30">Page de profil</h2>
        {{  form_start(form) }}
        {{  form_rest(form) }}
        <button class="mr-10 btn btn-primary">
            Mettre à jour
        </button>
        {{  form_end(form) }}
    </div>

    <div class="block mb-20">
        <h3 class="pb-30">Mes questions</h3>
        <ul>
        {% for question in app.user.questions %}
            <li class="mb-10">{{ question.title }}</li>    
        {% endfor %}
        </ul>
    </div>

    <div class="block mb-20">
        <h3 class="pb-30">Mes réponses</h3>
        <ul>
        {% for comment in app.user.comments %}
            <li class="mb-10">{{ comment.content | slice(0,50) }} ...</li>    
        {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/user/question.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil
{% endblock %}

{% block body %}

	<div class="block mb-20">
		<h3 class="pb-30">Mes questions</h3>
		<ul>
			{% for question in questions %}
				<li>
					<div class="pb-20 d-flex flex-row-nowrap justify-between align-center">
						<p  {% if question.rating > 0 %} 
                                class="rating-up text-small mr-10" 
                            {% elseif question.rating < 0 %} 
                                class="rating-down text-small mr-10" 
                            {% else %} 
                                class="text-small mr-10" 
                            {% endif %} >Vote: {{ question.rating }}
                        </p>
						<h3 class="mr-10">{{ question.title }}</h3>
						<p class="italic">{{ question.createdAt | date("d/m/Y") }}</p>
					</div>
					<p class="pb-20">{{ question.content }}</p>
				</li>
			{% endfor %}
		</ul>
	</div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.fullname }}{% endblock %}

{% block body %}

    <div class="block mb-20">
        <h2 class="pb-30">{{ user.fullname }}</h2>
        <div class="d-flex flex-row.nowrap">
            <img src="{{ asset(user.picture) }}" class="mr-10 profile-picture">
            <ul >
                <li class="mb-10">
                    <strong class="mr-10">Prénom: </strong>{{ user.firstname }}
                </li>
                <li class="mb-10">
                    <strong class="mr-10">Nom: </strong>{{ user.lastname }}
                </li>
                <li class="mb-10">
                    <strong class="mr-10">Email: </strong>{{ user.email }}
                </li>
            </ul>
        </div>
    </div>
    
    <div class="block mb-20">
        <h3 class="pb-30">Questions</h3>
        <ul>
        {% for question in user.questions %}
            <li class="mb-10">{{ question.title }}</li>    
        {% endfor %}
        </ul>
    </div>

    <div class="block mb-20">
        <h3 class="pb-30">Réponses</h3>
        <ul>
        {% for comment in user.comments %}
            <li class="mb-10">{{ comment.content | slice(0,50) }} ...</li>    
        {% endfor %}
        </ul>
    </div>
{% endblock %}